import type { User } from '../../domain/entities/User';
import type { Listing } from '../../domain/entities/Listing';
import type { RoomieProfile } from '../../domain/entities/RoomieProfile';
import type { Message } from '../../domain/entities/Message';
import type { Plan } from '../../domain/entities/Plan';
import type { Rating } from '../../domain/entities/Rating';
import { UserRepository } from '../repositories/UserRepository';
import { ListingRepository } from '../repositories/ListingRepository';
import { RoomieRepository } from '../repositories/RoomieRepository';
import { MessageRepository } from '../repositories/MessageRepository';
import { PlanRepository } from '../repositories/PlanRepository';
import { RatingRepository } from '../repositories/RatingRepository';

const SEED_KEY = 'uhome_seeded_v7';

const USERS: User[] = [
  {
    id: 'student-1',
    name: 'María García',
    email: 'maria.garcia@univalle.edu.co',
    password: 'Password1',
    role: 'student',
    university: 'Universidad del Valle',
    career: 'Ingeniería de Sistemas',
    age: 21,
    budget: { min: 300000, max: 600000 },
    preferences: { smoker: false, pets: false, schedule: 'tranquilo' },
    description: 'Estudiante de sistemas, me gusta el orden y la tranquilidad. Busco un lugar cómodo cerca de la universidad.',
    plan: 'premium',
    createdAt: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 'student-2',
    name: 'Carlos Rodríguez',
    email: 'carlos.r@icesi.edu.co',
    password: 'Password1',
    role: 'student',
    university: 'Universidad Icesi',
    career: 'Administración de Empresas',
    age: 22,
    budget: { min: 400000, max: 800000 },
    preferences: { smoker: false, pets: true, schedule: 'social' },
    description: 'Busco roomie sociable y responsable. Tengo un perro pequeño muy amigable.',
    plan: 'free',
    createdAt: '2025-01-20T10:00:00.000Z',
  },
  {
    id: 'owner-1',
    name: 'Lucía Martínez',
    email: 'lucia.m@gmail.com',
    password: 'Password1',
    role: 'owner',
    phone: '3101234567',
    propertyTypes: ['habitación', 'apartamento'],
    city: 'Cali',
    description: 'Propietaria de inmuebles en el norte de Cali. Alquilo a estudiantes universitarios.',
    plan: 'premium',
    createdAt: '2025-01-10T10:00:00.000Z',
  },
  {
    id: 'owner-2',
    name: 'Jorge Peña',
    email: 'jorge.pena@hotmail.com',
    password: 'Password1',
    role: 'owner',
    phone: '3209876543',
    propertyTypes: ['apartamento'],
    city: 'Cali',
    description: 'Propietario en Ciudad Jardín, Cali. Apartamentos bien ubicados para estudiantes.',
    plan: 'free',
    createdAt: '2025-01-12T10:00:00.000Z',
  },
  {
    id: 'student-3',
    name: 'Valentina López',
    email: 'valentina.lopez@univalle.edu.co',
    password: 'Password1',
    role: 'student',
    plan: 'free',
    university: 'Universidad del Valle',
    career: 'Ingeniería Industrial',
    age: 20,
    budget: { min: 500000, max: 900000 },
    preferences: { smoker: false, pets: false, schedule: 'tranquilo' },
    description: 'Estudiante de ingeniería, ordenada y responsable. Busco habitación cerca de Univalle.',
    createdAt: '2025-03-01T10:00:00.000Z',
  },
  {
    id: 'student-4',
    name: 'Sebastián Torres',
    email: 'sebastian.torres@icesi.edu.co',
    password: 'Password1',
    role: 'student',
    plan: 'free',
    university: 'Universidad Icesi',
    career: 'Diseño de Comunicación Visual',
    age: 23,
    budget: { min: 700000, max: 1400000 },
    preferences: { smoker: false, pets: true, schedule: 'social' },
    description: 'Diseñador en formación, creativo y sociable. Tengo un gato tranquilo.',
    createdAt: '2025-03-10T10:00:00.000Z',
  },
  {
    id: 'student-5',
    name: 'Camila Herrera',
    email: 'camila.herrera@javeriana.edu.co',
    password: 'Password1',
    role: 'student',
    plan: 'free',
    university: 'Pontificia Universidad Javeriana Cali',
    career: 'Medicina',
    age: 22,
    budget: { min: 800000, max: 1800000 },
    preferences: { smoker: false, pets: false, schedule: 'tranquilo' },
    description: 'Estudiante de medicina, busco lugar tranquilo y bien ubicado cerca de la Javeriana.',
    createdAt: '2025-03-15T10:00:00.000Z',
  },
  {
    id: 'admin-1',
    name: 'Administrador Uhome',
    email: 'admin@uhome.co',
    password: 'Admin2025',
    role: 'admin',
    createdAt: '2025-01-01T00:00:00.000Z',
  },
];

const LISTINGS: Listing[] = [
  {
    id: 'listing-1',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Estudio moderno totalmente equipado — Ciudad Jardín',
    price: 950000,
    city: 'Cali',
    zone: 'Ciudad Jardín',
    address: 'Cra. 98 # 16-45, Ciudad Jardín',
    type: 'habitación',
    rooms: 1,
    bathrooms: 1,
    description: 'Estudio minimalista en torre residencial con cocina integrada, mesón de trabajo y zona de comedor para dos personas. Decoración moderna en tonos neutros, totalmente amoblado. Edificio con portería 24h y zona de lavandería. A 5 min de Jardín Plaza y a 8 min de la Universidad Icesi. Servicios incluidos.',
    services: { internet: true, water: true, electricity: true, gas: false },
    images: [
      '/images/apt0/Screenshot-2026-06-04-at-10.32.50-PM.png',
      '/images/apt0/Screenshot-2026-06-04-at-10.33.02-PM.png',
      '/images/apt0/Screenshot-2026-06-04-at-10.32.57-PM.png',
      '/images/apt0/Screenshot-2026-06-04-at-10.33.08-PM.png',
    ],
    status: 'published',
    featured: true,
    featuredUntil: '2026-07-15T00:00:00.000Z',
    createdAt: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'listing-2',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Apartamento con vista panorámica 180° — Pance',
    price: 1800000,
    city: 'Cali',
    zone: 'Pance',
    address: 'Cll. 25 # 122-60, Pance',
    type: 'apartamento',
    rooms: 2,
    bathrooms: 1,
    description: 'Espectacular apartamento en piso 9 con ventanales de piso a techo y vista panorámica hacia los cerros de Pance. Sala-comedor amplio, luz natural todo el día, pisos en madera laminada. Ideal para dos estudiantes exigentes. Edificio con gimnasio, parqueadero y seguridad 24h. A 10 min de la Pontificia Universidad Javeriana Cali.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [
      '/images/apt1/Screenshot-2026-06-04-at-10.33.21-PM.png',
      '/images/apt1/Screenshot-2026-06-04-at-10.33.25-PM.png',
      '/images/apt1/Screenshot-2026-06-04-at-10.33.33-PM.png',
    ],
    status: 'published',
    createdAt: '2025-02-05T10:00:00.000Z',
  },
  {
    id: 'listing-3',
    ownerId: 'owner-2',
    ownerName: 'Jorge Peña',
    title: 'Apartamento contemporáneo cocina gourmet — Ciudad Jardín',
    price: 1500000,
    city: 'Cali',
    zone: 'Ciudad Jardín',
    address: 'Cra. 100 # 11-45, Ciudad Jardín',
    type: 'apartamento',
    rooms: 2,
    bathrooms: 1,
    description: 'Apartamento en torre residencial del sur de Cali con cocina de diseño, iluminación ambiental LED y vista nocturna de la ciudad. Acabados en madera y acero, electrodomésticos de alta gama. Zonas comunes con piscina y BBQ. A 5 min de la Universidad Icesi y centro comercial Jardín Plaza.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [
      '/images/apt2/Screenshot-2026-06-04-at-10.33.41-PM.png',
      '/images/apt2/Screenshot-2026-06-04-at-10.33.45-PM.png',
      '/images/apt2/Screenshot-2026-06-04-at-10.33.49-PM.png',
    ],
    status: 'published',
    createdAt: '2025-02-10T10:00:00.000Z',
  },
  {
    id: 'listing-4',
    ownerId: 'owner-2',
    ownerName: 'Jorge Peña',
    title: 'Habitación privada con baño propio — Bochalema',
    price: 750000,
    city: 'Cali',
    zone: 'Bochalema',
    address: 'Cra. 112 # 4-30, Bochalema',
    type: 'habitación',
    rooms: 1,
    bathrooms: 1,
    description: 'Habitación en casa restaurada con baño privado, estantería de diseño industrial, escritorio de trabajo y buena luz natural. Bochalema es uno de los sectores más tranquilos y arbolados del sur de Cali. Ambiente residencial silencioso, ideal para estudiantes de la Universidad del Valle o Javeriana. A 12 min de Ciudad Jardín.',
    services: { internet: true, water: true, electricity: true, gas: false },
    images: [
      '/images/apt3/Screenshot-2026-06-04-at-10.35.34-PM.png',
      '/images/apt3/Screenshot-2026-06-04-at-10.35.45-PM.png',
      '/images/apt3/Screenshot-2026-06-04-at-10.35.50-PM.png',
    ],
    status: 'published',
    createdAt: '2025-02-15T10:00:00.000Z',
  },
  {
    id: 'listing-5',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Apartamento amoblado con A/C y Smart TV — Ciudad Pacífica',
    price: 1200000,
    city: 'Cali',
    zone: 'Ciudad Pacífica',
    address: 'Cll. 18 # 105-20, Ciudad Pacífica',
    type: 'apartamento',
    rooms: 2,
    bathrooms: 1,
    description: 'Apartamento completamente amoblado con aire acondicionado split, Smart TV 43" y sala con sofá en L. Cocina equipada con nevera, microondas y estufa eléctrica. Edificio con portería, bicicletero y zona de lavandería. A 10 min de la Universidad Santiago de Cali. Tranquilo, seguro y con buena conexión al sur de la ciudad.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [
      '/images/apt4/Screenshot-2026-06-04-at-10.39.03-PM.png',
      '/images/apt4/Screenshot-2026-06-04-at-10.39.10-PM.png',
      '/images/apt4/Screenshot-2026-06-04-at-10.39.18-PM.png',
    ],
    status: 'published',
    createdAt: '2025-02-20T10:00:00.000Z',
  },
  {
    id: 'listing-6',
    ownerId: 'owner-2',
    ownerName: 'Jorge Peña',
    title: 'Apartamento open-concept cocina en mármol — Jamundí',
    price: 1450000,
    city: 'Cali',
    zone: 'Jamundí',
    address: 'Cll. 12 # 8-55, Jamundí',
    type: 'apartamento',
    rooms: 2,
    bathrooms: 1,
    description: 'Apartamento con diseño open-concept de última tendencia: cocina con isla en cuarzo blanco, canecas en madera natural e iluminación con bombillos Edison. Sala y comedor integrados, espacio luminoso y moderno. Edificio nuevo con ascensor, portería y parqueadero. A 5 min de la variante Jamundí–Cali. Ideal para dos estudiantes que buscan tranquilidad.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [
      '/images/apt5/Screenshot-2026-06-04-at-10.39.58-PM.png',
      '/images/apt5/Screenshot-2026-06-04-at-10.40.02-PM.png',
      '/images/apt5/Screenshot-2026-06-04-at-10.40.13-PM.png',
    ],
    status: 'published',
    createdAt: '2025-02-25T10:00:00.000Z',
  },
  {
    id: 'listing-7',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Apartamento piso 5 — mismo edificio Jamundí',
    price: 1400000,
    city: 'Cali',
    zone: 'Jamundí',
    address: 'Cll. 12 # 8-55 Apto 502, Jamundí',
    type: 'apartamento',
    rooms: 2,
    bathrooms: 1,
    description: 'Segunda unidad disponible en el mismo edificio, en piso 5 con mejor ventilación y vista despejada. Misma distribución open-concept: cocina con isla de cuarzo, sala y comedor integrados. Disponible de inmediato. Edificio con ascensor, portería y parqueadero de bicicletas.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [
      '/images/apt6/Screenshot-2026-06-04-at-10.39.58-PM.png',
      '/images/apt6/Screenshot-2026-06-04-at-10.40.02-PM.png',
      '/images/apt6/Screenshot-2026-06-04-at-10.40.13-PM.png',
    ],
    status: 'published',
    createdAt: '2025-03-01T10:00:00.000Z',
  },
  {
    id: 'listing-8',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Apartamento premium con zonas sociales — Pance',
    price: 2200000,
    city: 'Cali',
    zone: 'Pance',
    address: 'Cll. 23 # 124-10, Pance',
    type: 'apartamento',
    rooms: 2,
    bathrooms: 2,
    description: 'Apartamento de lujo en conjunto residencial cerrado rodeado de naturaleza en Pance. Zonas sociales de primer nivel: terraza con asador BBQ, jardín comunal, salón de juegos y gimnasio. Acabados en granito, cocina completamente dotada. Administración incluida. Seguridad 24h. A 5 min del ecoparque Pance y a 15 min de la Universidad Javeriana. La mejor opción para estudiantes que buscan calidad de vida en el sur de Cali.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [
      '/images/apt7/Screenshot-2026-06-04-at-10.40.41-PM.png',
      '/images/apt7/Screenshot-2026-06-04-at-10.40.45-PM.png',
      '/images/apt7/Screenshot-2026-06-04-at-10.40.52-PM.png',
    ],
    status: 'published',
    createdAt: '2025-03-05T10:00:00.000Z',
  },
];

const RATINGS: Rating[] = [
  {
    id: 'rating-1',
    fromUserId: 'student-1',
    toUserId: 'owner-1',
    score: 5,
    comment: 'Lucía es una propietaria excelente. El estudio en Ciudad Jardín estaba exactamente como se mostraba, muy limpio y bien equipado. Respondió todas mis dudas de inmediato y el proceso fue muy fácil.',
    createdAt: '2025-04-10T10:00:00.000Z',
  },
  {
    id: 'rating-2',
    fromUserId: 'student-2',
    toUserId: 'owner-1',
    score: 4,
    comment: 'Muy buena experiencia. El apartamento en Pance tiene una vista espectacular hacia los cerros. La propietaria estuvo disponible para cualquier inconveniente y lo resolvió rápidamente.',
    createdAt: '2025-04-15T10:00:00.000Z',
  },
  {
    id: 'rating-3',
    fromUserId: 'student-3',
    toUserId: 'owner-1',
    score: 5,
    comment: 'El mejor lugar que he arrendado desde que llegué a Cali. Las zonas sociales del conjunto son increíbles y el precio es justo para todo lo que incluye. 100% recomendado.',
    createdAt: '2025-05-02T10:00:00.000Z',
  },
  {
    id: 'rating-4',
    fromUserId: 'student-4',
    toUserId: 'owner-1',
    score: 5,
    comment: 'Superó mis expectativas. Ciudad Jardín es el sector perfecto para estudiar, tranquilo y bien conectado. Lucía es muy profesional y el apartamento está impecable.',
    createdAt: '2025-05-20T10:00:00.000Z',
  },
  {
    id: 'rating-5',
    fromUserId: 'student-5',
    toUserId: 'owner-1',
    score: 4,
    comment: 'Buena propietaria, muy organizada. El lugar estaba perfecto al momento de la entrega y los servicios funcionaban todos sin problema.',
    createdAt: '2025-06-01T10:00:00.000Z',
  },
  {
    id: 'rating-6',
    fromUserId: 'student-1',
    toUserId: 'owner-2',
    score: 4,
    comment: 'Jorge es un arrendador responsable y puntual. La habitación en Bochalema es muy tranquila, ideal para estudiar. El sector es seguro y hay buena conexión de transporte.',
    createdAt: '2025-04-20T10:00:00.000Z',
  },
  {
    id: 'rating-7',
    fromUserId: 'student-3',
    toUserId: 'owner-2',
    score: 3,
    comment: 'El apartamento está bien ubicado en Jamundí pero algunos electrodomésticos necesitaban mantenimiento al llegar. Jorge los arregló en menos de 24 horas, eso se valora.',
    createdAt: '2025-05-08T10:00:00.000Z',
  },
  {
    id: 'rating-8',
    fromUserId: 'student-4',
    toUserId: 'owner-2',
    score: 4,
    comment: 'Buena relación calidad-precio. El sector de Jamundí es muy seguro, silencioso y perfecto para concentrarse. Jorge siempre respondió rápido a los mensajes.',
    createdAt: '2025-05-25T10:00:00.000Z',
  },
  {
    id: 'rating-9',
    fromUserId: 'student-5',
    toUserId: 'owner-2',
    score: 5,
    comment: '¡Excelente! El apartamento open-concept es hermoso, exactamente como las fotos. Jorge fue muy atento durante todo el proceso de arrendamiento. Lo recomiendo totalmente.',
    createdAt: '2025-06-05T10:00:00.000Z',
  },
];

const PLANS: Plan[] = [
  {
    id: 'plan-free',
    name: 'Gratuito',
    price: 0,
    durationDays: 0,
    maxContacts: 3,
    maxListings: 3,
    canFeature: false,
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'plan-premium',
    name: 'Premium',
    price: 50000,
    durationDays: 30,
    maxContacts: null,
    maxListings: null,
    canFeature: true,
    active: true,
    createdAt: '2025-01-01T00:00:00.000Z',
  },
];

const ROOMIE_PROFILES: RoomieProfile[] = [
  {
    id: 'roomie-1',
    userId: 'student-1',
    name: 'María García',
    age: 21,
    university: 'Universidad del Valle',
    career: 'Ingeniería de Sistemas',
    preferences: { smoker: false, pets: 'no', schedule: 'tranquilo', order: 'alto' },
    budget: 500000,
    stayDuration: 12,
    description: 'Busco roomie ordenada/o, tranquila/o. Estudio mucho en las tardes así que prefiero ambiente sin mucho ruido. Me encanta cocinar y comparto mi comida.',
    createdAt: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'roomie-2',
    userId: 'student-2',
    name: 'Carlos Rodríguez',
    age: 22,
    university: 'Universidad Icesi',
    career: 'Administración de Empresas',
    preferences: { smoker: false, pets: 'sí', schedule: 'social', order: 'medio' },
    budget: 700000,
    stayDuration: 6,
    description: 'Soy social y organizado a mi manera. Tengo un perro pequeño (muy buena gente). Me gusta cocinar los fines de semana.',
    createdAt: '2025-02-05T10:00:00.000Z',
  },
];

const MESSAGES: Message[] = [
  {
    id: 'msg-1',
    senderId: 'student-1',
    receiverId: 'owner-1',
    content: '¡Hola! Me interesa la habitación en Granada. ¿Está disponible?',
    createdAt: '2025-03-01T10:00:00.000Z',
    read: true,
  },
  {
    id: 'msg-2',
    senderId: 'owner-1',
    receiverId: 'student-1',
    content: '¡Hola María! Sí, sigue disponible. ¿Te gustaría verla este fin de semana?',
    createdAt: '2025-03-01T11:00:00.000Z',
    read: true,
  },
];

export function seedIfNeeded(): void {
  if (localStorage.getItem(SEED_KEY)) return;
  UserRepository.seed(USERS);
  ListingRepository.seed(LISTINGS);
  PlanRepository.seed(PLANS);
  RoomieRepository.seed(ROOMIE_PROFILES);
  MessageRepository.seed(MESSAGES);
  RatingRepository.seed(RATINGS);
  localStorage.setItem(SEED_KEY, '1');
}
