import type { User } from '../../domain/entities/User';
import type { Listing } from '../../domain/entities/Listing';
import type { RoomieProfile } from '../../domain/entities/RoomieProfile';
import type { Message } from '../../domain/entities/Message';
import { UserRepository } from '../repositories/UserRepository';
import { ListingRepository } from '../repositories/ListingRepository';
import { RoomieRepository } from '../repositories/RoomieRepository';
import { MessageRepository } from '../repositories/MessageRepository';

const SEED_KEY = 'uhome_seeded_v2';

const USERS: User[] = [
  {
    id: 'student-1',
    name: 'María García',
    email: 'maria.garcia@univalle.edu.co',
    password: 'Password1',
    role: 'student',
    university: 'Universidad del Valle',
    career: 'Ingeniería de Sistemas',
    age: 21,
    budget: { min: 300000, max: 600000 },
    preferences: { smoker: false, pets: false, schedule: 'tranquilo' },
    description: 'Estudiante de sistemas, me gusta el orden y la tranquilidad. Busco un lugar cómodo cerca de la universidad.',
    createdAt: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 'student-2',
    name: 'Carlos Rodríguez',
    email: 'carlos.r@icesi.edu.co',
    password: 'Password1',
    role: 'student',
    university: 'Universidad Icesi',
    career: 'Administración de Empresas',
    age: 22,
    budget: { min: 400000, max: 800000 },
    preferences: { smoker: false, pets: true, schedule: 'social' },
    description: 'Busco roomie sociable y responsable. Tengo un perro pequeño muy amigable.',
    createdAt: '2025-01-20T10:00:00.000Z',
  },
  {
    id: 'owner-1',
    name: 'Lucía Martínez',
    email: 'lucia.m@gmail.com',
    password: 'Password1',
    role: 'owner',
    phone: '3101234567',
    propertyTypes: ['habitación', 'apartamento'],
    city: 'Cali',
    description: 'Propietaria de inmuebles en el norte de Cali. Alquilo a estudiantes universitarios.',
    createdAt: '2025-01-10T10:00:00.000Z',
  },
  {
    id: 'owner-2',
    name: 'Jorge Peña',
    email: 'jorge.pena@hotmail.com',
    password: 'Password1',
    role: 'owner',
    phone: '3209876543',
    propertyTypes: ['apartamento'],
    city: 'Cali',
    description: 'Propietario en Ciudad Jardín, Cali. Apartamentos bien ubicados para estudiantes.',
    createdAt: '2025-01-12T10:00:00.000Z',
  },
  {
    id: 'admin-1',
    name: 'Administrador Uhome',
    email: 'admin@uhome.co',
    password: 'Admin2025',
    role: 'admin',
    createdAt: '2025-01-01T00:00:00.000Z',
  },
];

const LISTINGS: Listing[] = [
  {
    id: 'listing-1',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Habitación individual en Granada',
    price: 550000,
    city: 'Cali',
    zone: 'Granada',
    address: 'Cra. 9 con Calle 14N',
    type: 'habitación',
    rooms: 1,
    bathrooms: 1,
    description: 'Habitación amplia y luminosa con baño compartido. A 10 min de la Universidad Icesi. Incluye servicios, WiFi de alta velocidad y acceso a cocina y sala común.',
    services: { internet: true, water: true, electricity: true, gas: false },
    images: [],
    status: 'published',
    featured: true,
    featuredUntil: '2025-06-30T00:00:00.000Z',
    createdAt: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'listing-2',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Apartamento moderno en San Fernando',
    price: 1200000,
    city: 'Cali',
    zone: 'San Fernando',
    address: 'Calle 5 con Carrera 40',
    type: 'apartamento',
    rooms: 2,
    bathrooms: 1,
    description: 'Apartamento nuevo, bien ubicado, cerca de la Universidad del Valle. Ideal para 2 estudiantes. Piso 4 con buena vista. Parqueadero disponible.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [],
    status: 'published',
    createdAt: '2025-02-05T10:00:00.000Z',
  },
  {
    id: 'listing-3',
    ownerId: 'owner-2',
    ownerName: 'Jorge Peña',
    title: 'Habitación en Ciudad Jardín',
    price: 480000,
    city: 'Cali',
    zone: 'Ciudad Jardín',
    address: 'Cra. 100, Ciudad Jardín',
    type: 'habitación',
    rooms: 1,
    bathrooms: 1,
    description: 'Habitación en casa compartida de 4 estudiantes. Zona muy segura y con buena vida universitaria. A 15 min de la Universidad Icesi.',
    services: { internet: true, water: true, electricity: false, gas: false },
    images: [],
    status: 'published',
    createdAt: '2025-02-10T10:00:00.000Z',
  },
  {
    id: 'listing-4',
    ownerId: 'owner-2',
    ownerName: 'Jorge Peña',
    title: 'Apartamento estudio en Santa Teresita',
    price: 900000,
    city: 'Cali',
    zone: 'Santa Teresita',
    address: 'Av. 6N con Calle 23N',
    type: 'apartamento',
    rooms: 1,
    bathrooms: 1,
    description: 'Estudio completamente amoblado, cocina integrada, buena ubicación. Ideal para estudiante independiente. Cerca de la Universidad Autónoma de Occidente.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [],
    status: 'published',
    createdAt: '2025-02-15T10:00:00.000Z',
  },
  {
    id: 'listing-5',
    ownerId: 'owner-1',
    ownerName: 'Lucía Martínez',
    title: 'Habitación en El Peñón',
    price: 380000,
    city: 'Cali',
    zone: 'El Peñón',
    address: 'Calle 5 con Carrera 2',
    type: 'habitación',
    rooms: 1,
    bathrooms: 1,
    description: 'Habitación económica en casa colonial restaurada. Ideal para estudiantes de la Universidad del Valle o Javeriana Cali. Zona histórica y tranquila.',
    services: { internet: true, water: true, electricity: true, gas: false },
    images: [],
    status: 'published',
    createdAt: '2025-02-20T10:00:00.000Z',
  },
  {
    id: 'listing-6',
    ownerId: 'owner-2',
    ownerName: 'Jorge Peña',
    title: 'Apartamento 3 hab. en Versalles',
    price: 1500000,
    city: 'Cali',
    zone: 'Versalles',
    address: 'Av. 1N con Calle 18N',
    type: 'apartamento',
    rooms: 3,
    bathrooms: 2,
    description: 'Gran apartamento perfecto para 3 estudiantes. Zona residencial tranquila, parques cercanos, buena conexión de transporte.',
    services: { internet: true, water: true, electricity: true, gas: true },
    images: [],
    status: 'published',
    createdAt: '2025-02-25T10:00:00.000Z',
  },
];

const ROOMIE_PROFILES: RoomieProfile[] = [
  {
    id: 'roomie-1',
    userId: 'student-1',
    name: 'María García',
    age: 21,
    university: 'Universidad del Valle',
    career: 'Ingeniería de Sistemas',
    preferences: { smoker: false, pets: 'no', schedule: 'tranquilo', order: 'alto' },
    budget: 500000,
    stayDuration: 12,
    description: 'Busco roomie ordenada/o, tranquila/o. Estudio mucho en las tardes así que prefiero ambiente sin mucho ruido. Me encanta cocinar y comparto mi comida.',
    createdAt: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'roomie-2',
    userId: 'student-2',
    name: 'Carlos Rodríguez',
    age: 22,
    university: 'Universidad Icesi',
    career: 'Administración de Empresas',
    preferences: { smoker: false, pets: 'sí', schedule: 'social', order: 'medio' },
    budget: 700000,
    stayDuration: 6,
    description: 'Soy social y organizado a mi manera. Tengo un perro pequeño (muy buena gente). Me gusta cocinar los fines de semana.',
    createdAt: '2025-02-05T10:00:00.000Z',
  },
];

const MESSAGES: Message[] = [
  {
    id: 'msg-1',
    senderId: 'student-1',
    receiverId: 'owner-1',
    content: '¡Hola! Me interesa la habitación en Granada. ¿Está disponible?',
    createdAt: '2025-03-01T10:00:00.000Z',
    read: true,
  },
  {
    id: 'msg-2',
    senderId: 'owner-1',
    receiverId: 'student-1',
    content: '¡Hola María! Sí, sigue disponible. ¿Te gustaría verla este fin de semana?',
    createdAt: '2025-03-01T11:00:00.000Z',
    read: true,
  },
];

export function seedIfNeeded(): void {
  if (localStorage.getItem(SEED_KEY)) return;
  UserRepository.seed(USERS);
  ListingRepository.seed(LISTINGS);
  RoomieRepository.seed(ROOMIE_PROFILES);
  MessageRepository.seed(MESSAGES);
  localStorage.setItem(SEED_KEY, '1');
}
